### ISSUE TITLE
add unicode number forms

### ISSUE THREAD

**Issue by derhuerst** [sindresorhus/figures#12]
[Number Forms like `¼`](https://en.wikipedia.org/wiki/Number_Forms) would really make sense, since they are non-ASCII and have a really nice fallback (`1/4`).

**Comment by sindresorhus** [comment]
Can you show an example of how it would look like using it from `figures`?

**Comment by derhuerst** [comment]
Something like `figures.1by4` or `figures.oneByFour` with yields in `¼`.

**Comment by sindresorhus** [comment]
Probably not `figures.1by4` as it's invalid JS, but yeah, sounds useful. PR welcome :)

**Comment by sindresorhus** [comment]
While I have you here. I've been thinking about adding a method to replace unicode with the fallbacks. So you could do `figures('¼ yezz')` and it would return `'¼ yezz'` on OS X / Linux and `'1/4 yezz'` on Windows. What do you think?

**Comment by derhuerst** [comment]
> Probably not `figures.1by4` as it's invalid JS, but yeah, sounds useful. PR welcome :)

You're right. One could use `figures[1by4]` or `figures['1by4']`.

> So you could do figures('¼ yezz') and it would return '¼ yezz' on OS X / Linux and '1/4 yezz' on Windows. What do you think?

Isnt that essentially template strings? (`\`${figures.tick} yezz\``)

**Comment by sindresorhus** [comment]
> Isnt that essentially template strings?

Not really. It could be a tagged template literal [0]. The point is to let you use the original unicode character in the string and have it replaced with fallbacks when not supported. In your example you have to use the verbose descriptive property access.

[0]:

```
figures`¼ yezz`
```

**Comment by SamVerschueren** [comment]
That would be a nice addition. Not sure if it should be implemented in `figures` or in a separate `figures-replace` module.

**Comment by sindresorhus** [comment]
@SamVerschueren I think it should be here. Could be the main export actually.

```js
const figures = require('figures');

console.log(figures.tick);

console.log(figures`¼ yezz`);
```

**Comment by SamVerschueren** [comment]
I'm ok with that. Just wanted to make sure you considered a separate module ;).

**Comment by sindresorhus** [comment]
My unrelated idea continues here: https://github.com/sindresorhus/figures/issues/14

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/figures/issues/13.
