### ISSUE TITLE
Add list of figures in the readme

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/figures#17]
I'm not 100% sure, so didn't do a PR yet, because it might be too much.

It would be nice to have an overview of all the figures in the readme. Now you always have to dig into the code in order to see which symbols are supported.

Something like this might do

| Name  | Real OSes | Windows |
|-------|:---------:|:-------:|
| tick  |     ✔︎     |    √    |
| cross |     ✖     |    ×    |
| star |     ★     |    *    |
| ... |          |        |

**Comment by sindresorhus** [comment]
👍 Good idea.

I imagine it can simply be a script that when `npm run make`, creates the Markdown and adds it to the readme.

**Comment by SamVerschueren** [comment]
I started creating a script for it but in order for it to work, I think we should extract the figures to a JSON file. I can't iterate over them because the `figures` object only has to figures of the current platform.

**Comment by SamVerschueren** [comment]
I have a script that works. So if you agree with the json file solution, I will do a PR.

On the other hand, should we change the implementation just to support documenting it?

On the other other hand, it might be cleaner for people to make PRs for new figures if they only have to change a JSON file and don't have to work in the JavaScript.

**Comment by kevva** [comment]
If we really don't want a JSON, you could use https://github.com/shinnn/pretend-platform to generate the figures for each platform. But I don't see any harm in moving them to a JSON either.

**Comment by sindresorhus** [comment]
Maybe overwrite `process.platform` with each OS and require each time using [`require-uncached`](https://github.com/sindresorhus/require-uncached)?

**Comment by SamVerschueren** [comment]
That solution works!
