### ISSUE TITLE
Support browsers?

### ISSUE THREAD

**Issue by hollowdoor** [sindresorhus/figures#21]
Is there any possibility this library will get browser support?

The main thing preventing usage in the browser is this check in index.js:

```javascript
const platform = process.platform;
```

Maybe it should be:

```javascript
const platform = (function(){
    if(typeof process === 'object'){
        return process.platform || 'linux';
    }
    return 'linux'; //Maybe this should be something else.
})();
```

I don't know what else might need to be changed.

**Comment by sindresorhus** [comment]
Why would you want this in the browser? Unicode works fine there.

**Comment by hollowdoor** [comment]
It's the dependency chain. Suppose I want to make use of figures in another library. This other library is something I want to use in node, but I also want to support the browser.

I have three choices.

1. conditional loading of figures with a backfill (or reverse pollyfill to undo figures)
2. make a new library that does what figures does, but supports browsers as well
3. ask here if this library can be made to work in browsers so I don't have to do 2, and 3

I understand a reticence to support browsers, but I thought it couldn't hurt to ask.

Also names instead of escape gobbledygook is much nicer to use. I can define my own variables, but then that would be like making my own library. And with static es2015 modules in the works conditional loading is not desirable. Conditional compilation is an option, but that also means creating another library.

Not that I don't appreciate your work. I don't want to make you think I'm just complaining. I know there's a delicate balance of features without bloat in module development. If I have to burn some time making my own solution I will.

**Comment by kevva** [comment]
Works fine if you're using `webpack` or `browserify` (which I assume you're doing if you're working with `node` modules in browsers) since they shim the `process` object.

```js
'use strict';
const figures = require('figures');

console.log(figures('✔ check'));
console.log(figures('✖ cross'));
console.log(figures('★ star'));
console.log(figures('▇ square'));
console.log(figures('◉ circleFilled'));
```

<img width="864" alt="screen shot 2017-09-18 at 23 57 56" src="https://user-images.githubusercontent.com/709159/30566714-6f3a08aa-9ccd-11e7-87f7-bfa3fb7bb502.png">

**Comment by hollowdoor** [comment]
@kevva I'm using rollup. There is a natives plugin for rollup. But I wanted to use this module as a dependency to another module. I would rather not import natives to a another module.
