### ISSUE TITLE
Transpile to ES5

### ISSUE THREAD

**Issue by yxliang01** [sindresorhus/figures#22]
I think it would be better if we can have this package distributed with ES5. Otherwise, this would break lots of packages that doesn't support ES6 new features like `const`.

Thanks

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
