### ISSUE TITLE
cucumber-js breaks on IE11 because of IE11 incompatible syntax

### ISSUE THREAD

**Issue by rhpijnacker** [sindresorhus/figures#23]
See https://github.com/cucumber/cucumber-js/issues/1011.
Would it be possible to publish this package with IE11 compatible syntax?

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
