### ISSUE TITLE
Please consider exporting `main` & `windows`

### ISSUE THREAD

**Issue by sramam** [sindresorhus/figures#30]
I am trying to test the CLI of a cross-platform app that uses inquirer, which depends upon `figures`.

The issue is that tests fail with 
```
  -       >( ) Pepperoni␊
  -        ( ) Ham␊
  -        ( ) Ground Meat␊
  -        ( ) Bacon␊
  +       ❯◯ Pepperoni␊
  +        ◯ Ham␊
  +        ◯ Ground Meat␊
  +        ◯ Bacon␊
            = The Cheeses = ␊
  -        (*) Mozzarella␊
  +        ◉ Mozzarella␊
```

The test can easily replace the output to have a normalized form of figures when CLI is being tested so this does not occur. However, currently, there is no programatic way to getting to the `figures.windows` symbols on my `macos` (or vice versa). 

I can create a manual copy, but that seems brittle.

**Comment by sramam** [comment]
Interestingly, as part of this exercise, discovered that `main.circleQuestionMark` & 
`main.questionMarkPrefix` cannot be used to create RegExp. I don't need it for my purpose, but thought I'd document it here...

**Comment by Richienb** [comment]
@sramam So, you want both sets of symbols to be exported?

**Comment by sramam** [comment]
> So, you want both sets of symbols to be exported?

yes please.

> Have you tried using escape-string-regexp?

good point. I didn't actually have a problem so didn't look closely enough, but makes sense that one should use this. 


Somedays I wonder if there is anything useful in JS land that @sindresorhus hasn't already published to npm, years ago. *That'll* be the real unicorn! :)

**Comment by Richienb** [comment]
@sindresorhus What's your opinion on this?

**Comment by sindresorhus** [comment]
Yeah, sure. Makes sense for testing.
