### ISSUE TITLE
Display single-character percentages on Windows

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/figures#40]
Most percentages single characters are available on Windows CP850. However, this library currently falls back to using ASCII such as `1/3`.

Ubuntu 20.10 Gnome terminal:

![unix_3](https://user-images.githubusercontent.com/8136211/112218748-653add80-8c24-11eb-9556-e72bb28c03f8.png)

Windows 10 `cmd.exe` (CP850):

![windows_3](https://user-images.githubusercontent.com/8136211/112218756-6835ce00-8c24-11eb-9d39-9747ea7d276b.png)

However, `1/7`, `1/9` and `1/10` are not supported on CP850.

Removing support for those three (arguably not-often-used) characters would allow switching to single characters percentages instead. This would also provide with a more consistent cross-platform experience.

What do you think?

**Comment by sindresorhus** [comment]
> Removing support for those three (arguably not-often-used) characters

I don't think we should remove them. Rather just let them keep using the ASCII output. Yes, it will be inconsistent, but as you said, they're not very often used, especially not together.

**Comment by ehmicky** [comment]
Sounds good!
Fixed in #45.
