### ISSUE TITLE
 empty space instead of tick symbol

### ISSUE THREAD

**Issue by vadimgoncharov** [sindresorhus/figures#5]
Very strange bug in Mac OS 10.10 iTerm:

```
require('figures').tick
// produce empty symbol
```

I don't know why this happens, but it fixed with:

```
Object.keys(symbols).forEach(function(key) {
    symbols[key] = fromCharCode(symbols[key].charCodeAt(0));
});
```

Example:

```
var figures = require('figures');
var patchedFigures = require('../figures');

Object.keys(figures).forEach(function(key) {
    console.log('"%s" "%s"', patchedFigures[key], figures[key]);
});
// see screenshot below
```

[screenshot](https://www.dropbox.com/s/aaxcj0dyt0lt3c5/Screenshot%202014-11-18%2017.37.45.png?dl=0)

**Comment by ehmicky** [comment]
See https://github.com/sindresorhus/figures/pull/102: the invisible character is variation selection 15, `U+FE0E`.
