### ISSUE TITLE
Expose the replacement function as a named export instead

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/figures#50]
Would there be some benefits to expose the replacement function as a named export instead of default export?

If so, should this be a breaking change (by removing the default export), or should this be backward-compatible (by keeping it)?

**Comment by sindresorhus** [comment]
> Would there be some benefits to expose the replacement function as a named export instead of default export?

I don't know. Would there be? You're the one asking.

**Comment by ehmicky** [comment]
In my opinion, having a variable that is both a function and a "traditional" object might have some drawbacks: 
  - This can be confusing for users.
  - It can come with some surprise if the user is checking for the variable type (for example with `is-plain-obj`)
  - This can lead to some unexpected behavior when copying the variable. For example `{...var}` would keep the object properties, but not the function, while `var.bind()` would do the opposite.
  - This can complicate TypeScript types.

On the other side, some users find default exports simpler than named exports.

Overall, I think using a named export is more proper, but I was curious what your thoughts on this were?

**Comment by sindresorhus** [comment]
Even if we moved the replacement function to a named function, the rest should still stay a default export (I will move to ESM soon, so having both will not be a problem).

I don't feel strongly about this. Any suggestion on the name for the replacement function? `replaceSymbols()`?

**Comment by ehmicky** [comment]
`replaceSymbols()` sounds good :+1: 

Just to make sure, are you suggesting the following: moving the function to a named export called `replaceSymbols()`, and keep the default export, but only for the figures (not for that function)?

**Comment by sindresorhus** [comment]
> Just to make sure, are you suggesting the following: moving the function to a named export called replaceSymbols(), and keep the default export, but only for the figures (not for that function)?

Correct.

Actually, I think we can just move to ESM. My big ESM is in a month, but we can start early. I have a lot of modules to go through.

**Comment by ehmicky** [comment]
Sounds good.

Are there some PRs from your other repositories I could use as example? This would streamline both the implementation and the review.

**Comment by sindresorhus** [comment]
> Are there some PRs from your other repositories I could use as example? This would streamline both the implementation and the review.

https://github.com/sindresorhus/manage-wifi/commit/89dfe2596bf814a6e23e7e6534b8e72be699b138

https://github.com/sindresorhus/debounce-fn/commit/e07dc3fb151a08b28c86a69a42025fad399da0c0

**Comment by ehmicky** [comment]
This was released in https://github.com/sindresorhus/figures/releases/tag/v4.0.0.
