### ISSUE TITLE
Add figures for subscript numbers

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/figures#52]
What are your thoughts on adding figures for subscript numbers? They display well on all environments:

Ubuntu 20.10, Gnome terminal:

![unix_6](https://user-images.githubusercontent.com/8136211/112360243-63c7ee80-8cd2-11eb-9d22-1c322928d2eb.png)

Windows 10, `cmd.exe` (CP850):

![windows_6](https://user-images.githubusercontent.com/8136211/112360239-632f5800-8cd2-11eb-8b04-afb73ed10ae9.png)

I checked on macOS default terminal, and it looks good too :+1:

**Comment by sindresorhus** [comment]
👍

**Comment by ehmicky** [comment]
Fixed by #63.
