### ISSUE TITLE
Add figures for some common mathematical symbols

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/figures#53]
What are your thoughts on adding figures for the following mathematical symbols?

```
≈ ≠ ≡ ≤ ≥ ∞
``` 

They display well on all environments:

Ubuntu 20.10, Gnome terminal:

![unix_5](https://user-images.githubusercontent.com/8136211/112360603-c7521c00-8cd2-11eb-9e78-f6f4c2baee98.png)

Windows 10, `cmd.exe` (CP850):

![windows_5](https://user-images.githubusercontent.com/8136211/112360584-c3be9500-8cd2-11eb-9332-eedd55d68931.png)

I checked on macOS default terminal, and it looks good too :+1:

**Comment by sindresorhus** [comment]
👍

**Comment by ehmicky** [comment]
Done in #62.
