### ISSUE TITLE
Add figures for musical notes

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/figures#54]
What are your thoughts on adding figures for musical notes?

```
♪ ♫
``` 

They display well on all environments:

Ubuntu 20.10, Gnome terminal:

![unix_4](https://user-images.githubusercontent.com/8136211/112360882-16984c80-8cd3-11eb-9d7b-217c7f09f916.png)

Windows 10, `cmd.exe` (CP850):

![windows_4](https://user-images.githubusercontent.com/8136211/112360903-1b5d0080-8cd3-11eb-92ab-83a2ab41d65a.png)

I checked on macOS default terminal, and it looks good too :+1:

**Comment by sindresorhus** [comment]
👍

**Comment by ehmicky** [comment]
Fixed by #61.
