### ISSUE TITLE
 Add figures for triangles and lozenges

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/figures#55]
What are your thoughts on adding figures for triangles and lozenges? 

They display well on all environments:

Ubuntu 20.10, Gnome terminal:

![unix_3](https://user-images.githubusercontent.com/8136211/112361057-49424500-8cd3-11eb-9949-8a0263e3e3c8.png)

Windows 10, `cmd.exe` (CP850):

![windows_3](https://user-images.githubusercontent.com/8136211/112361077-4e9f8f80-8cd3-11eb-9bf4-998ea511eba5.png)

I checked on macOS default terminal, and it looks good too :+1: 

Note: this library is already having one triangle with the `play` figure, but it might be nice to have it as well as a regular "big triangle pointing to the right" figure.

**Comment by sindresorhus** [comment]
👍

**Comment by sindresorhus** [comment]
> Note: this library is already having one triangle with the play figure, but it might be nice to have it as well as a regular "big triangle pointing to the right" figure.

I agree. The `play` one can just reference this one.

**Comment by ehmicky** [comment]
Fixed by #64.
