### ISSUE TITLE
Add figures for box lines

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/figures#56]
What are your thoughts on adding figures for box lines? 

They display well on all environments. The following screenshots shows them both as individual characters, and displayed on several rows/columns.

Ubuntu 20.10, Gnome terminal:

![unix_2](https://user-images.githubusercontent.com/8136211/112361366-94f4ee80-8cd3-11eb-82dc-cdb5606bde14.png)

Windows 10, `cmd.exe` (CP850):

![windows_2](https://user-images.githubusercontent.com/8136211/112361382-99210c00-8cd3-11eb-99e7-6fb3652587af.png)

I checked on macOS default terminal, and it looks good too :+1: 

I believe all of the above are useful, but offering a subset is also an option. The high number of characters is mostly due to different variants of dashes and boldness.

At the moment, the only related figure in this library is `line` (`U-2500`) (not included above).

**Comment by sindresorhus** [comment]
👍  To the person that ends up submitting a PR for this, good luck naming all of these.

**Comment by ehmicky** [comment]
I think we can use system of prefixes and suffixes (although I agree the names will most likely be verbose).

**Comment by ehmicky** [comment]
Proposal for naming: `line${directions}${variant}`

`directions` can be:
  - `Horizontal`, e.g. ━
  - `Vertical`, e.g. ┃
  - `BottomRight`, `BottomLeft`, `TopRight` or `TopLeft`, e.g. ┏  ┓ ┗  ┛
  - `TopBottomRight`, `TopBottomLeft`, `BottomLeftRight` or `TopLeftRight`, e.g. ┣  ┫  ┳  ┻
  - `TopBottomLeftRight`, e.g. ╋
  - `DiagonalCross` for ╳
  - `DiagonalFalling` for ╲
  - `DiagonalRising` for ╱

`variant` can be:
  - nothing/empty, e.g. │
  - `Bold`, e.g. ┃
  - `Double`, e.g. ║
  - `Dash0`, `Dash1`, ..., `Dash15` for all dash variants, e.g. ┇

When a symbol combines several `variant`s, they are appended to each `direction`. For example, the most complex name would be `lineTopBoldBottomLeftBoldRight` for ╃

Exception:  ‾ (`U-203e`) would be named `overline` because it is singular in the fact that it is not centered, and not really meant as a box line.

What do you think?

**Comment by sindresorhus** [comment]
That sounds good to me.

**Comment by sindresorhus** [comment]
> I would also suggest leaving out ‾ (U-203e) as it is not centered and not really meant as a box line.

👍

**Comment by ehmicky** [comment]
Done at #70.
