### ISSUE TITLE
Add figures for fill characters

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/figures#57]
What are your thoughts on adding figures for fill characters? 

They display well on all environments. The following screenshots shows them both as individual characters, and displayed on several rows/columns.

Ubuntu 20.10, Gnome terminal:

![unix_1](https://user-images.githubusercontent.com/8136211/112361787-0cc31900-8cd4-11eb-8c71-03f214df249f.png)

Windows 10, `cmd.exe` (CP850):

![windows_1](https://user-images.githubusercontent.com/8136211/112361810-10ef3680-8cd4-11eb-8b9d-bac4058d4798.png)

On macOS default terminal, they do not combine perfectly vertically. I do not think there is a better character available though (but please let me know if I'm wrong). Also, many macOS users might have better terminal / fonts / settings which would show this better.

![macos_1](https://user-images.githubusercontent.com/8136211/112361994-3e3be480-8cd4-11eb-830b-9d6f6a5a1fa5.png)

I believe all of the above are useful:
  - The first 4 fill the whole character, which is good when "painting" a whole area, with 4 different shades
  - `U-25a0` is useful for progress bar, as it has margins both up and down, but not left and right
  - The other 4 are useful as half-full characters: left, right, up, down

**Comment by sindresorhus** [comment]
👍

**Comment by ehmicky** [comment]
Note: there are already 3 fill characters in this library:

```
square, Unix: ▇ (U-2587), Windows: █ (U-2588)
squareSmall, Unix: ◻ (U-25fb), Windows: □ (U-25a1)
squareSmallFilled, Unix: ◼ (U-25fc), Windows: ■ (U-25a0)
```

The characters for `squareSmall` and `squareSmallFilled` overlap oddly depending on the environment, which explains the different Unicode codepoints used. Also those characters have margins all around them, making them different from the ones mentioned in the top comment.

When it comes to `square`, the situation is a little more odd. ▇ (U-2587) does not display correctly on `cmd.exe`, while █ (U-2588) does. There is a difference between them: U-2587 has a 1-pixel top margin, while U-2588 has no margins. It seems to me this inconsistency might lead to environment-specific visual bugs, depending on whether the user expects a margin (example: progress bar) or not (example: "painting" a whole area). 

I am thinking it might be a good thing to deprecate that character in favor of the fill characters which have clear meanings when it comes to margins. Another option would be to make `square` U-2588 instead of U-2587 on Unix. This would technically be a breaking change.

What are your thoughts on this?

**Comment by sindresorhus** [comment]
> Another option would be to make square U-2588 instead of U-2587 on Unix. This would technically be a breaking change.

I think that would be more correct anyway:
- https://www.compart.com/en/unicode/U+2587
- https://www.compart.com/en/unicode/U+2588
If you look at their names.

**Comment by ehmicky** [comment]
First part done at #66.
