### ISSUE TITLE
Figures in PuTTY do not display correctly at all

### ISSUE THREAD

**Issue by adam-beck** [sindresorhus/figures#6]
I have two machines running Ubuntu with the same fonts/colors. One is Vagrant VM which I SSH into with PuTTY and the other is a regular laptop running the OS. When trying to use these figures within PuTTY they are either partially cut off or they are not displayed at all. Some fonts display them better than others but I am using Inconsolata for Powerline. 

The laptop works great.

I don't really expect this to be fixed as it is a fringe case but was more or less wondering if someone was able to tweak some settings (in PuTTY, Ubuntu, etc) to get these to work?

**Comment by sindresorhus** [comment]
https://www.google.com/search?q=putty+unicode

**Comment by adam-beck** [comment]
I have unicode characters working. Some of them just look like complete crap.

**Comment by vmadman** [comment]
@adam-beck in the unlikely event that you still care about this, after all of this time, I was able to get characters to display correctly by switching to the "DejaVu Sans Mono" font, as suggested on SuperUser:

* https://superuser.com/questions/393834/how-to-configure-putty-to-display-these-characters

I've only tested a limited subset of the characters, but the main takeaway, for me, was the fact that its definitely a PuTTY issue and it's highly influenced by the font that you choose.

Hope this helps someone...
