### ISSUE TITLE
Linux kernel console support

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/figures#73]
Approximately half of the figures do not display correctly in the [Linux kernel console](https://en.wikipedia.org/wiki/Linux_console):
  - The following do not display correctly, but the `windows` fallback does: `✔  ℹ ⚠ ✖ ◼ ◯ ◉ ◌ ◎ ◉ ◯ ☒ ☐ ❯ △ ☰ ෴`
  - The following do not display correctly, nor does the `windows` fallback (when there is one): `₀ ₁ ₂ ₃ ₄ ₅ ₆ ₇ ₈ ₉ ★ ✶ ㋡ ☺ ⬢ ♦ ◆ ♦ ◇ ◊ ◻ □ ▓ ▀ ▄ ▌ ▐ ⌂ ♥ ♪ ♫ ↔ ↕`
  - Half of the `line*` figures do not display correctly (mostly the ones with mixed stroke styles)
  - All single-character percentages do not display correctly, except for `½ ¼ ¾`

Which solution would be better?
  1. Document lack of support for the Linux kernel console
  2. Detect the Linux kernel console using the `TERM=linux` environment variable and provide a new set of fallback characters for it

(Please note that I tested this library on 22 terminals [listed here](https://github.com/ehmicky/cross-platform-terminal-characters#terminals). The only ones which did not work are the Linux kernel console, xterm and cmder. I have opened issues for each of those separately.)

**Comment by sindresorhus** [comment]
`1`

**Comment by ehmicky** [comment]
Done in #76.
