### ISSUE TITLE
cmder support

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/figures#74]
[cmder](https://github.com/cmderdev/cmder) is a popular Windows terminal (22,000+ GitHub stars).

The following figures do not display correctly with its default font:
  - `₀ ₁ ₂ ₃ ₄ ₅ ₆ ₇ ₈ ₉`
  - `▴ ▾ ◂ ▸`
  - `․`
  - More than half of box drawing lines, including all horizontal/vertical dashed lines. The [list here](https://github.com/ehmicky/cross-platform-terminal-characters#box-drawing) covers most of the lines supported by cmder.

Which solution would be better?
  1. Document lack of support for cmder
  2. Detect cmder using the `CMDER_ROOT` environment variable and provide a new set of fallback characters for it
  3. Fix the `windows` fallback for the above characters so they display correctly on `cmder`. This would impact all other Windows terminals, not only cmder.

**Comment by sindresorhus** [comment]
I would go with `1`. People should just use Windows Terminal instead if they're not bound to cmd.exe. We could document that. However, what is your opinion about this?

**Comment by ehmicky** [comment]
I think `figures` users could probably choose their terminal. However, if they are developing libraries, they would need to forward that advice to their own users.

Judging by the popularity of `cmder`, I am guessing it might have some features its users like. However, its popularity might be due to a void that Windows Terminal will fill soon.

From that standpoint, I think solution `1.` would be good. :+1:

**Comment by sindresorhus** [comment]
> From that standpoint, I think solution 1. would be good. 👍

👍

**Comment by ehmicky** [comment]
Done in #76.

**Comment by sindresorhus** [comment]
@ehmicky You strictly don't need to comment with a link to a PR. I already get a notification for the PR, and the PR links to the issue, which makes the issue show a link to the PR.
