### ISSUE TITLE
xterm support

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/figures#75]
`xterm` does not display the following figures correctly: `⬢ ⅐ ⅑ ⅒ ㋡ ෴ ❯ ⓧ Ⓘ ⓞ ⚠`
Please note this is for `xterm`, not for `xterm.js` nor for Linux kernel console.

Which solution would be better?
  - Document lack of support for `xterm`
  - Detect `xterm` using the `XTERM_VERSION` environment variable and provide a new set of fallback characters for it

**Comment by sindresorhus** [comment]
Are anyone actually using `xterm` directly?

**Comment by ehmicky** [comment]
I am not sure as I could not find any usage data about terminal usage.

If you think `xterm` is not worth supporting though, we might want to document the lack of support in `readme.md`?

**Comment by sindresorhus** [comment]
Let's just go with `1`.

**Comment by ehmicky** [comment]
Done in #76.
