### ISSUE TITLE
Main `cross` character is incorrect

### ISSUE THREAD

**Issue by gibson042** [sindresorhus/figures#92]
(discovered while working on ava test result accessibility: https://github.com/avajs/ava/pull/3082 )

The main `cross` character is U+2716 HEAVY MULTIPLICATION X "✖︎", but for accessibility (and proper contrast with `tick` U+2714 HEAVY CHECK MARK "✔︎") it should instead be U+2718 HEAVY BALLOT X "✘︎".

**Comment by ehmicky** [comment]
Hi @gibson042,

I have tried to display `U+2714 ✔`, `U+2716 ✖` and `U+2718 ✘` on [the following list of ~20 terminals](https://github.com/ehmicky/cross-platform-terminal-characters#terminals) with the default fonts. Apparently they all display correctly except:
  - None of them displays correctly on Windows Console Host (`cmd.exe`, Powershell) and mintty/Git-for-Windows
  - Only `U+2718 ✘` displays correctly on the Linux kernel console

From a style standpoint, ti seems to me that `U+2718 ✘` is less bold and more slanted, so is closer to `U+2714 ✔`. From that angle, this makes sense to me as well.

That being said, could you please add some additional description as to what specifically makes `U+2718 ✘` more accessible than `U+2716 ✖`, and for which type of accessibility? Thanks!

**Comment by gibson042** [comment]
Sure, I'm primarily concerned about proper semantics and the corresponding consequences upon vision-impaired users. For example, screen readers are notoriously bad at symbols, and for example VoiceOver reads U+2716 HEAVY MULTIPLICATION X "✖︎" as "multiplication symbol", which is appropriate for that software because the character is in fact a multiplication symbol. But that has no obvious connection to negative status such as a test failure, and the fact that they are visually similar is insufficient reason to consider them as interchangeable.

**Comment by ehmicky** [comment]
This makes sense, thanks for explaining! :+1:
